all:
	make -C client
	make -C config

clean:
	make -C client clean
	make -C config clean

fclean:
	make -C client fclean
	make -C config fclean

re:
	make -C client re
	make -C config re

.PHONY: all clean fclean re
